version: "3.7"

services:
  database_ignite_desafio_tests:
    image: postgres
    container_name: database_ignite_desafio_tests
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: fin-api
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
